# Generated by Django 3.2.25 on 2024-10-24 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en-route', 'en-route'), ('pickup', 'pickup'), ('dropoff', 'dropoff')], default='en-route', max_length=10)),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('dropoff_latitude', models.FloatField()),
                ('dropoff_longitude', models.FloatField()),
                ('pickup_time', models.DateTimeField()),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_rides', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(limit_choices_to={'role': 'rider'}, on_delete=django.db.models.deletion.CASCADE, related_name='rider_rides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
