# Generated by Django 3.2.25 on 2024-10-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20241024_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_rider',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver'), ('rider', 'Rider')], default='rider', max_length=10),
        ),
    ]
