# Generated by Django 3.2.25 on 2024-10-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20241024_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('driver', 'Driver'), ('rider', 'Rider')], default='rider', max_length=10),
        ),
    ]
